<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-14UM7ID" failures="1" tests="3" name="SwagLabsProject" time="11.614" errors="0" timestamp="2023-10-18T15:32:29 CEST">
  <testcase classname="Tests.ProductsTest" name="userCanAddProduct" time="0.439"/>
  <testcase classname="Tests.ProductsTest" name="userCanRemoveProduct" time="0.416"/>
  <testcase classname="Tests.ProductsTest" name="productIsStillInTheCartAfterLogout" time="2.143">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at Tests.ProductsTest.productIsStillInTheCartAfterLogout(ProductsTest.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- productIsStillInTheCartAfterLogout -->
</testsuite> <!-- SwagLabsProject -->
